services:
  db:
    # Mariadb Datenbankserver
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    secrets:
      - db-password
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    expose:
      - 3306
      - 33060
    networks:
      - backend

  webserver:
    # Apache php server
    build: webserver
    container_name: pr0-webserver
    ports:
      - '80:80'
    depends_on:
      - db
    networks:
      - backend
      - frontend
    volumes:
      - ./daten/:/data
    secrets:
      - db-password
volumes:
  db-data: 
secrets:
  db-password:
    file: db/password.txt
networks:
  backend:
  frontend: